name: sisantri
description: "Aplikasi gamifikasi untuk Pondok Pesantren Mahasiswa Al-Awwabin Sukarame – Bandar Lampung"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  firebase_messaging: ^15.1.3

  # Google Sign In
  google_sign_in: ^6.2.1

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5

  # Clean Architecture
  equatable: ^2.0.5

  # UI & Utils
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1

  # Excel Export
  excel: ^4.0.3
  path_provider: ^2.1.4
  open_file: ^3.5.1

  # NFC/RFID
  nfc_manager: ^4.0.2

  # Icons & Animations
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.12
  riverpod_generator: ^2.4.3
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0

flutter:
  uses-material-design: true
